public class CC_SalesforcetoAthenaResponse {
    public string name {get;set;}
    public string dataJson {get;set;}
    public string queueId {get;set;}
    public string type {get;set;}
    public string jsonType {get;set;}
    public string expireOnUTC {get;set;}
    public string postponeUntilUTC {get;set;}
    public string source {get;set;}
    public string event {get;set;}
    public string accountId {get;set;}
    public string allycontactId {get;set;}
    public string emergencycontactId {get;set;}
}